In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [6]:
arr=np.array([1,2,3])

In [7]:
arr_2d=np.array([[1,2,3],[4,5,6]])

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.arange(0,10,4)

array([0, 4, 8])

In [20]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [21]:
np.random.rand(3,2)

array([[0.46708619, 0.82955064],
       [0.9352484 , 0.09724755],
       [0.75054644, 0.78335986]])

In [22]:
np.random.randn(3,2)

array([[ 0.31948911, -0.53711833],
       [-0.28481579, -0.47692685],
       [-0.74834977, -0.99803285]])

In [23]:
arr=np.array([[1,2,3],[4,5,6]])

In [24]:
print(arr.shape)

(2, 3)


In [25]:
print(arr.ndim)

2


In [26]:
print(arr.size)

6


In [28]:
a=np.array([1,2,3])

In [29]:
b=np.array([4,5,6])

In [30]:
a+b

array([5, 7, 9])

In [31]:
a*b

array([ 4, 10, 18])

In [32]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [33]:
A=np.array([[1,2],[3,4]])

In [34]:
B=np.array([[5,6],[7,8]])

In [35]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [36]:
A@B

array([[19, 22],
       [43, 50]])

In [37]:
arr=np.array([1,2,3,4])

In [38]:
arr.sum()

np.int64(10)

In [39]:
arr.mean()

np.float64(2.5)

In [40]:
arr.min()

np.int64(1)

In [41]:
arr.std()

np.float64(1.118033988749895)

In [42]:
arr=np.array([1,2,3,4,5])

In [43]:
arr[0]

np.int64(1)

In [44]:
arr[1:4]

array([2, 3, 4])

In [46]:
arr[::2]

array([1, 3, 5])

In [47]:
arr=np.array([1,2,3,4,5])

In [48]:
mask=arr>3

In [49]:
arr[mask]

array([4, 5])

In [67]:
arr=np.arange(6)

In [68]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [69]:
a=np.array([1,2])

In [70]:
b=np.array([3,4])

In [54]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [55]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [56]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [57]:
a=np.array([1,2,3])

In [ ]:
a+5#[6,7,8]

In [59]:
np.save('array.npy',arr)

In [61]:
loaded_arr=np.load('array.npy')